import type { Menu, MenuItem, Modifier } from "./types.js";
import { MenuSchema } from "./types.js";
import { menuImageUrl } from "./menuImages.js";

const menu: Menu = {
  categories: [
    { id: "cat-burgers", name: "Burgers", sortOrder: 0 },
    { id: "cat-sandwiches", name: "Sandwiches", sortOrder: 1 },
    { id: "cat-sides", name: "Sides", sortOrder: 2 },
    { id: "cat-drinks", name: "Drinks", sortOrder: 3 },
  ],
  modifiers: [
    { id: "lettuce", displayName: "Lettuce", kind: "default", priceDeltaCents: 0 },
    { id: "tomato", displayName: "Tomato", kind: "default", priceDeltaCents: 0 },
    { id: "onion", displayName: "Onion", kind: "default", priceDeltaCents: 0 },
    { id: "pickle", displayName: "Pickles", kind: "default", priceDeltaCents: 0 },
    { id: "extra_pickles", displayName: "Extra pickles", kind: "extra", priceDeltaCents: 75 },
    { id: "bacon", displayName: "Bacon", kind: "extra", priceDeltaCents: 199 },
    { id: "cheese", displayName: "Cheese", kind: "extra", priceDeltaCents: 99 },
    { id: "jalapeno", displayName: "Jalapeños", kind: "extra", priceDeltaCents: 79 },
    { id: "ranch", displayName: "Ranch drizzle", kind: "extra", priceDeltaCents: 49 },
    { id: "flavor_cola", displayName: "Coca-Cola", kind: "extra", priceDeltaCents: 0 },
    { id: "flavor_diet_coke", displayName: "Diet Coke", kind: "extra", priceDeltaCents: 0 },
    { id: "flavor_coke_zero", displayName: "Coke Zero", kind: "extra", priceDeltaCents: 0 },
    { id: "flavor_sprite", displayName: "Sprite", kind: "extra", priceDeltaCents: 0 },
    { id: "flavor_rootbeer", displayName: "Root Beer", kind: "extra", priceDeltaCents: 0 },
    { id: "flavor_dr_pepper", displayName: "Dr Pepper", kind: "extra", priceDeltaCents: 0 },
    { id: "flavor_fanta", displayName: "Fanta Orange", kind: "extra", priceDeltaCents: 0 },
    { id: "flavor_ginger_ale", displayName: "Ginger Ale", kind: "extra", priceDeltaCents: 0 },
    { id: "size_large", displayName: "Large size", kind: "extra", priceDeltaCents: 79 },
  ],
  items: [
    {
      id: "item-classic-burger",
      categoryId: "cat-burgers",
      name: "Classic Bistro Burger",
      description: "Seared patty, brioche bun, house sauce.",
      basePriceCents: 1299,
      imageUrl: menuImageUrl("item-classic-burger"),
      defaultModifierIds: ["lettuce", "tomato", "onion", "pickle"],
      allowedExtraModifierIds: ["extra_pickles", "bacon", "cheese", "jalapeno", "ranch"],
      pairingItemIds: ["item-fries", "item-fountain-drink"],
      tags: ["popular"],
    },
    {
      id: "item-bbq-bacon-burger",
      categoryId: "cat-burgers",
      name: "BBQ Bacon Burger",
      description: "Smoky BBQ glaze, crispy bacon, cheddar, onion rings.",
      basePriceCents: 1499,
      imageUrl: menuImageUrl("item-bbq-bacon-burger"),
      defaultModifierIds: ["lettuce", "tomato", "pickle"],
      allowedExtraModifierIds: ["extra_pickles", "bacon", "cheese", "jalapeno", "ranch"],
      pairingItemIds: ["item-fries", "item-fountain-drink"],
      tags: ["popular"],
    },
    {
      id: "item-spicy-chicken",
      categoryId: "cat-sandwiches",
      name: "Spicy Chicken Sandwich",
      description: "Crispy thigh, slaw, chili aioli.",
      basePriceCents: 1199,
      imageUrl: menuImageUrl("item-spicy-chicken"),
      defaultModifierIds: ["lettuce", "pickle"],
      allowedExtraModifierIds: ["bacon", "cheese", "jalapeno", "ranch"],
      pairingItemIds: ["item-fries", "item-fountain-drink"],
      tags: ["spicy", "popular"],
      spicy: true,
    },
    {
      id: "item-grilled-cheese",
      categoryId: "cat-sandwiches",
      name: "Truffle Grilled Cheese",
      description: "Three cheeses, truffle butter, sourdough.",
      basePriceCents: 999,
      imageUrl: menuImageUrl("item-grilled-cheese"),
      defaultModifierIds: [],
      allowedExtraModifierIds: ["bacon", "jalapeno", "ranch"],
      pairingItemIds: ["item-tomato-soup", "item-lemonade"],
      tags: ["vegetarian"],
    },
    {
      id: "item-fries",
      categoryId: "cat-sides",
      name: "Herb Fries",
      description: "Crisp fries, rosemary salt.",
      basePriceCents: 499,
      imageUrl: menuImageUrl("item-fries"),
      defaultModifierIds: [],
      allowedExtraModifierIds: ["ranch"],
      pairingItemIds: ["item-classic-burger", "item-spicy-chicken"],
      tags: ["side"],
    },
    {
      id: "item-tomato-soup",
      categoryId: "cat-sides",
      name: "Tomato Basil Soup",
      description: "Cup of soup with croutons.",
      basePriceCents: 599,
      imageUrl: menuImageUrl("item-tomato-soup"),
      defaultModifierIds: [],
      allowedExtraModifierIds: [],
      pairingItemIds: ["item-grilled-cheese"],
      tags: ["vegetarian"],
    },
    {
      id: "item-fountain-drink",
      categoryId: "cat-drinks",
      name: "Fountain Drink",
      description: "Unlimited refills. Pick one soda: Coke, Diet Coke, Coke Zero, Sprite, and more.",
      basePriceCents: 279,
      imageUrl: menuImageUrl("item-fountain-drink"),
      defaultModifierIds: ["flavor_cola"],
      allowedExtraModifierIds: [
        "flavor_cola",
        "flavor_diet_coke",
        "flavor_coke_zero",
        "flavor_sprite",
        "flavor_rootbeer",
        "flavor_dr_pepper",
        "flavor_fanta",
        "flavor_ginger_ale",
        "size_large",
      ],
      pairingItemIds: ["item-fries", "item-classic-burger", "item-bbq-bacon-burger"],
      tags: ["drink", "popular"],
    },
    {
      id: "item-lemonade",
      categoryId: "cat-drinks",
      name: "House Lemonade",
      description: "Fresh lemon, light mint.",
      basePriceCents: 399,
      imageUrl: menuImageUrl("item-lemonade"),
      defaultModifierIds: [],
      allowedExtraModifierIds: [],
      pairingItemIds: ["item-classic-burger", "item-fries"],
      tags: ["drink"],
    },
    {
      id: "item-iced-tea",
      categoryId: "cat-drinks",
      name: "Iced Black Tea",
      description: "Brewed daily, served chilled.",
      basePriceCents: 349,
      imageUrl: menuImageUrl("item-iced-tea"),
      defaultModifierIds: [],
      allowedExtraModifierIds: [],
      pairingItemIds: ["item-spicy-chicken"],
      tags: ["drink"],
    },
    {
      id: "item-water",
      categoryId: "cat-drinks",
      name: "Still Water",
      description: "500ml bottle.",
      basePriceCents: 249,
      imageUrl: menuImageUrl("item-water"),
      defaultModifierIds: [],
      allowedExtraModifierIds: [],
      pairingItemIds: [],
      tags: ["drink"],
    },
  ],
};

export const MENU_DATA_VERSION = 7;

export function getSeedMenu(): Menu {
  return MenuSchema.parse(menu);
}

export function modifierById(menuData: Menu, id: string): Modifier | undefined {
  return menuData.modifiers.find((m) => m.id === id);
}

export function itemById(menuData: Menu, id: string): MenuItem | undefined {
  return menuData.items.find((i) => i.id === id);
}
